### ISSUE TITLE
Element Android does not support displaying <blockquote> formatted_body text in room messages (non-thread)

### ISSUE THREAD

**Issue by mwnu** [etkecc/baibot#17]
Element-web and SchildiChat-android do support displaying it though.

In rooms, `<blockquote>`  is treated as [fallbacks for rich replies](https://spec.matrix.org/v1.11/client-server-api/#fallbacks-for-rich-replies). In Speech-to-Text-only configurations, text messages will be sent to the room, appearing like this:

```
{
    "body": "> 🦻 This is a voice message converted to text.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<blockquote>\n<p>🦻 This is a voice message converted to text.</p>\n</blockquote>\n",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$Ok7EqJNG13lq1dhA3MfhfmlNrMq2f9WPoHnkm70VE7U"
      }
    },
    "msgtype": "m.notice"
  }
  ```
Unable to display properly

However, if Text Generation is enabled, the text will be included in the thread and can be displayed normally:

  ```
  {
    "body": "> 🦻 This is a voice message converted to text.",
    "format": "org.matrix.custom.html",
    "formatted_body": "<blockquote>\n<p>🦻 This is a voice message converted to text.</p>\n</blockquote>\n",
    "m.relates_to": {
      "event_id": "$Ok7EqJNG13lq1dhA3MfhfmlNrMq2f9WPoHnkm70VE7U",
      "is_falling_back": true,
      "m.in_reply_to": {
        "event_id": "$Ok7EqJNG13lq1dhA3MfhfmlNrMq2f9WPoHnkm70VE7U"
      },
      "rel_type": "m.thread"
    },
    "msgtype": "m.notice"
  }
  ```

**Comment by spantaleev** [comment]
Thanks for bringing this up!

I have adjusted the default behavior for transcription replies (outside of threads) to not use `> 🦻` prefixing.
Messages are:

- still sent as [m.notice](https://spec.matrix.org/v1.11/client-server-api/#mnotice) (not [m.text](https://spec.matrix.org/v1.11/client-server-api/#mtext))
- reacted to by the bot via 🦻

Both of these actions indicate that this is not a bot message, but a transcription based on something it "heard".

--------

This new behavior probably improves (or fixes) your issue, and also fixes issue #14 at the same time.

This feature is part of the new [1.2.0 release](https://github.com/etkecc/baibot/blob/36fdb466335dbaf35e72192f5194a22fca913b50/CHANGELOG.md#2024-10-01-version-120).
